FROM nginx:alpine
COPY ./aw-webui /usr/share/nginx/html
# Optional: SPA routing fix
RUN echo 'server { listen 80; root /usr/share/nginx/html; index index.html; location / { try_files $uri $uri/ /index.html; } }' > /etc/nginx/conf.d/default.conf
